version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test2"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_password"
    ports:
        - "46873:5432"
  web:
    depends_on:
        - "postgres"
    build: .
    ports:
        - "8002:8000"
    extra_hosts:
        - "host.docker.internal:host-gateway"