from environs import Env

env = Env()

env.read_env()


ACCESS_TOKEN_EXPIRE_MINUTES = env.int("ACCESS_TOKEN_EXPIRE_MINUTES")
ALGORITHM = env.str("ALGORITHM")
SECRET_KEY = env.str("SECRET_KEY")
DATABASE_URL = env.str("DATABASE_URL")
#
# DATABASE_URL = "db.sqlite"
# ACCESS_TOKEN_EXPIRE_MINUTES = 30
# ALGORITHM = "HS256"
# SECRET_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1Nzg3NjM3MywiaWF0IjoxNjU3ODc2MzczfQ.oM174h2BGvM_t5vvSgDjEd-CKupavEfT9z4Hoc0RxnQ"
